services:
  cr-backend:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb16:5432/example_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: V3m02468.
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    command: mvn spring-boot:run
    networks:
      - my_network_cr

networks:
  my_network_cr:
    external: true
